version: '3.8'

services:
  ai_agent:
    image: iamaduck/ai_agent:latest
    container_name: ai_agent
    ports:
      - "8501:8501"  # 映射Streamlit默认端口
    volumes:
      - ./.env:/app/.env           # 映射.env文件
      - ./data:/app/data           # 映射data目录
      - ./outputs:/app/outputs     # 映射outputs目录
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1  # 确保Python输出不被缓存，便于查看日志